apiVersion: sagemaker.aws.amazon.com/v1
kind: TrainingJob
metadata:
  name: k8s-sm-dist-training-script3
spec:
    hyperParameters:
        - name: learning-rate
          value: "0.001"
        - name: weight-decay
          value: "0.0002"
        - name: batch-size
          value: "256"
        - name: momentum
          value: "0.9"
        - name: optimizer
          value: "adam"
        - name: epochs
          value: "20"
        - name: sagemaker_program
          value: 'cifar10-multi-gpu-horovod-sagemaker.py'
        - name: sagemaker_submit_directory
          value: 's3://cis188-test-eks/training-scripts/sourcedir.tar.gz'
        - name: sagemaker_region
          value: 'us-east-1'
        - name: sagemaker_mpi_custom_mpi_options
          value: "-verbose --NCCL_DEBUG=INFO -x OMPI_MCA_btl_vader_single_copy_mechanism=none"
        - name: sagemaker_mpi_enabled
          value: "true"
        - name: sagemaker_mpi_num_of_processes_per_hoste
          value: "1"
        - name: tensorboard_logs
          value: "s3://cis188-test-eks/tensorboard_logs/k8s-sm-2x1-workers-2"
    algorithmSpecification:
        trainingImage: 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:1.15.2-gpu-py27-cu100-ubuntu18.04
        #763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.4.1-gpu-py27-cu110-ubuntu18.04
        trainingInputMode: File
        metricDefinitions: 
         - name: val_acc
           regex: 'val_acc: ([0-9\\.]+)'
    roleArn: arn:aws:iam::120970087180:role/cis188-sagemaker
    region: us-east-1
    outputDataConfig:
        s3OutputPath: s3://cis188-test-eks/jobs/
    resourceConfig:
        instanceCount: 2
        instanceType: "ml.c4.xlarge"
        volumeSizeInGB: 5
    stoppingCondition:
        maxRuntimeInSeconds: 86400
    inputDataConfig:
        - channelName: train
          dataSource:
            s3DataSource:
                s3DataType: S3Prefix
                s3Uri: s3://cis188-test-eks/cifar10-dataset/train
                s3DataDistributionType: FullyReplicated
          compressionType: None
        - channelName: validation
          dataSource:
            s3DataSource:
                s3DataType: S3Prefix
                s3Uri: s3://cis188-test-eks/cifar10-dataset/validation
                s3DataDistributionType: FullyReplicated
          compressionType: None
        - channelName: eval
          dataSource:
            s3DataSource:
                s3DataType: S3Prefix
                s3Uri: s3://cis188-test-eks/cifar10-dataset/eval
                s3DataDistributionType: FullyReplicated
          compressionType: None
    tags:
      - key: tagKey
        value: tagValue
